#!/bin/bash
yt-dlp -a ./vodlinks.txt \
  -f "bestvideo[height<=1080][vcodec^=av01]+bestaudio/bestvideo[height<=1080][vcodec^=vp09]+bestaudio/bestvideo[height<=1080]+bestaudio/best" \
  --merge-output-format mkv \
  --download-archive downloaded_list.txt \
  --fragment-retries infinite \
  --concurrent-fragments 3 \
  -o "${PWD}/vods/%(release_date>%Y-%m-%d)s - %(title)s [%(id)s].%(ext)s" \
  2>> errors.log

